// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelayServer.Data;

#nullable disable

namespace RelayServer.Data.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    partial class RelayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("RelayServer.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnLibraryScanComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnNewMediaAdded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnTaskFailed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnUserCreated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnWhisperComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SetupComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbApiKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NotifyOnLibraryScanComplete = false,
                            NotifyOnNewMediaAdded = false,
                            NotifyOnTaskFailed = false,
                            NotifyOnUserCreated = false,
                            NotifyOnWhisperComplete = false,
                            SetupComplete = false
                        });
                });

            modelBuilder.Entity("RelayServer.Domain.AudioTrackInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("AudioTracks");
                });

            modelBuilder.Entity("RelayServer.Domain.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMetadataRefreshAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetadataEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataRefreshIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WhisperEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("RelayServer.Domain.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cast")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ImdbScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("KeyframesExtracted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MetadataRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RottenTomatoesScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrickplayGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WhisperCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WhisperQueued")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("SeasonId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("RelayServer.Domain.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CronSchedule")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ScheduledTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Library",
                            CronSchedule = "0 2 * * *",
                            IsEnabled = true,
                            Key = "scan_libraries",
                            LastStatus = 0,
                            Name = "Scan Media Libraries"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Library",
                            CronSchedule = "0 3 * * *",
                            IsEnabled = true,
                            Key = "refresh_metadata",
                            LastStatus = 0,
                            Name = "Refresh Metadata"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Library",
                            CronSchedule = "0 4 * * *",
                            IsEnabled = true,
                            Key = "generate_trickplay",
                            LastStatus = 0,
                            Name = "Generate Trickplay Images"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Library",
                            CronSchedule = "0 4 * * *",
                            IsEnabled = true,
                            Key = "extract_chapters",
                            LastStatus = 0,
                            Name = "Extract Chapter Images"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Library",
                            IsEnabled = false,
                            Key = "extract_keyframes",
                            LastStatus = 0,
                            Name = "Keyframe Extractor"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Library",
                            CronSchedule = "0 1 * * *",
                            IsEnabled = true,
                            Key = "whisper_queue",
                            LastStatus = 0,
                            Name = "Whisper Transcription Queue"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Maintenance",
                            CronSchedule = "0 0 * * 0",
                            IsEnabled = true,
                            Key = "clean_transcode_cache",
                            LastStatus = 0,
                            Name = "Clean Transcode Cache"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Maintenance",
                            CronSchedule = "0 0 * * 0",
                            IsEnabled = true,
                            Key = "clean_logs",
                            LastStatus = 0,
                            Name = "Clean Log Directory"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Maintenance",
                            CronSchedule = "0 0 1 * *",
                            IsEnabled = true,
                            Key = "clean_activity_log",
                            LastStatus = 0,
                            Name = "Clean Activity Log"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Maintenance",
                            CronSchedule = "0 0 1 * *",
                            IsEnabled = true,
                            Key = "optimize_database",
                            LastStatus = 0,
                            Name = "Optimize Database"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Maintenance",
                            CronSchedule = "0 0 1 * *",
                            IsEnabled = true,
                            Key = "user_data_cleanup",
                            LastStatus = 0,
                            Name = "User Data Cleanup"
                        });
                });

            modelBuilder.Entity("RelayServer.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("RelayServer.Domain.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ImdbScore")
                        .HasColumnType("REAL");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MetadataRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RottenTomatoesScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("RelayServer.Domain.SubtitleTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("SubtitleTracks");
                });

            modelBuilder.Entity("RelayServer.Domain.TaskRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId");

                    b.ToTable("TaskRuns");
                });

            modelBuilder.Entity("RelayServer.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RelayServer.Domain.UserLibraryAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique();

                    b.ToTable("UserLibraryAccess");
                });

            modelBuilder.Entity("RelayServer.Domain.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAudioLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSubtitleLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackQuality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("RelayServer.Domain.WatchProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAudioLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSubtitleLanguage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("WatchProgress");
                });

            modelBuilder.Entity("RelayServer.Domain.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("RelayServer.Domain.AudioTrackInfo", b =>
                {
                    b.HasOne("RelayServer.Domain.MediaItem", "MediaItem")
                        .WithMany("AudioTracks")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("RelayServer.Domain.MediaItem", b =>
                {
                    b.HasOne("RelayServer.Domain.Library", "Library")
                        .WithMany("Items")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelayServer.Domain.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Library");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RelayServer.Domain.Season", b =>
                {
                    b.HasOne("RelayServer.Domain.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("RelayServer.Domain.Series", b =>
                {
                    b.HasOne("RelayServer.Domain.Library", "Library")
                        .WithMany("Series")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("RelayServer.Domain.SubtitleTrack", b =>
                {
                    b.HasOne("RelayServer.Domain.MediaItem", "MediaItem")
                        .WithMany("Subtitles")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("RelayServer.Domain.TaskRun", b =>
                {
                    b.HasOne("RelayServer.Domain.ScheduledTask", "ScheduledTask")
                        .WithMany("Runs")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("RelayServer.Domain.UserLibraryAccess", b =>
                {
                    b.HasOne("RelayServer.Domain.Library", "Library")
                        .WithMany("UserAccess")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelayServer.Domain.User", "User")
                        .WithMany("LibraryAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayServer.Domain.UserSettings", b =>
                {
                    b.HasOne("RelayServer.Domain.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("RelayServer.Domain.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayServer.Domain.WatchProgress", b =>
                {
                    b.HasOne("RelayServer.Domain.MediaItem", "MediaItem")
                        .WithMany("WatchProgress")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelayServer.Domain.User", "User")
                        .WithMany("WatchProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayServer.Domain.WatchlistItem", b =>
                {
                    b.HasOne("RelayServer.Domain.MediaItem", "MediaItem")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelayServer.Domain.User", "User")
                        .WithMany("Watchlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayServer.Domain.Library", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Series");

                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("RelayServer.Domain.MediaItem", b =>
                {
                    b.Navigation("AudioTracks");

                    b.Navigation("Subtitles");

                    b.Navigation("WatchProgress");

                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("RelayServer.Domain.ScheduledTask", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("RelayServer.Domain.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("RelayServer.Domain.Series", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("RelayServer.Domain.User", b =>
                {
                    b.Navigation("LibraryAccess");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("WatchProgress");

                    b.Navigation("Watchlist");
                });
#pragma warning restore 612, 618
        }
    }
}
